# Generated by Django 4.1 on 2023-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="rtsp",
        ),
        migrations.AddField(
            model_name="monitor",
            name="source",
            field=models.TextField(default=""),
        ),
    ]
