# Generated by Django 4.1 on 2023-03-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detect_time", models.DateTimeField(auto_now_add=True)),
                ("person", models.IntegerField(default=0)),
                ("head_without_helmet", models.IntegerField(default=0)),
                ("head_with_helmet", models.IntegerField(default=0)),
                ("img", models.ImageField(upload_to="")),
                (
                    "monitor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.monitor",
                    ),
                ),
            ],
        ),
    ]
