# Generated by Django 4.1 on 2023-03-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detect", "0002_rename_detectresult_detect"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detect",
            old_name="monitor_id",
            new_name="monitor",
        ),
    ]
