# Generated by Django 4.1 on 2023-04-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
        ("detect", "0005_alter_result_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.monitor",
                    ),
                ),
            ],
        ),
    ]
