# Generated by Django 4.1 on 2023-04-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detect", "0006_messagecache"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageCache",
        ),
    ]
