# Generated by Django 4.1 on 2023-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=20)),
                ("source", models.TextField(default="")),
                ("helmet_detect", models.BooleanField(default=True)),
            ],
        ),
    ]
